### ISSUE TITLE
feature request: nested virtualization

### ISSUE THREAD

**Issue by aybabtme** [moby/hyperkit#127]
It would be great if the `vmx` CPU flag was possible to pass inside VMs created by hyperkit, so that, in example, one could run hypervisors in Docker.

**Comment by ijc25** [comment]
This would indeed be awesome, but you should be aware that it would be an _enormous_ amount of work to implement (this assumes that `Hypervisor.framework` exposes the required underlying hardware functionality), not to mention QA etc. As always, PRs are welcome of course.

**Comment by aybabtme** [comment]
@ijc25 haha yup I'm aware, I just thought it would be good to make the issue for tracking/know that there's interest 👍

**Comment by katiewasnothere** [comment]
Is there any update for this? Additionally, can someone explain more of what this would entail?

**Comment by Bacto** [comment]
FYI, I've found an other way to have CPU nesting by using docker-machine + VMware Fusion (I'm on macOS).

**Comment by katiewasnothere** [comment]
@Bacto Could you further explain?

**Comment by justincormack** [comment]
@katiewasnothere no update - its still an enormous amount of work, and as far as we know no one is working on it... As @Bacto mentions, VMWare Fusion can run nested virt (so you could use LinuxKit or any other VM and use nested KVM); in addition Google Cloud now supports nested KVM.

**Comment by pvtmert** [comment]
hi there,
looks like that is a long standing request, where you count me as one too!

fyi virtualbox and some-others support this, maybe veertu (https://veertu.com) may help because they had desktop application (much like virtualbox but simpler, using hypervisor.framework) and it had been open sourced before (fork/clone: https://github.com/tithomas1/vdhh)

maybe this helps?
https://github.com/tithomas1/vdhh/blob/master/vmm/x86_cpuid.c

**Comment by ijc** [comment]
Nested virtualisation is not just passing the vmx flag to the guest. You also need to implement a complete emulation of the processor's vmx subsystem, this is an *enormous* task.

So, I think we need to clearly set some expectations here: 

Nested virtualisation in Hyperkit is not going to happen unless someone shows up who is willing to contribute multiple person months of engineering effort to the problem. My initial estimate would be 6+ months and that would be for someone who is already very familiar with x86 virtualisation. None of the existing contributors that we are aware of have any plans to work on this at all in any way.

So my overall recommendation to anyone waiting for this functionality is: Don't. Unfortunately it's very unlikely to happen unless a new contributor appears specifically to implement this.
