### ISSUE TITLE
Clarify what can be done without superuser permissions

### ISSUE THREAD

**Issue by copumpkin** [moby/hyperkit#136]
I'm quite intrigued by the possibility of unprivileged VMs in macOS and am wondering what HyperKit functionality I'd be missing out on by running it as non-root, and how fundamental that is to the model.

(this ticket was prompted by @puffnfresh's tweet https://twitter.com/puffnfresh/status/869875923553734656)

**Comment by rneugeba** [comment]
the only bit which requires root is VMnet for networking and you can use VPNKit for that without requiring root. [LinuxKit](https://github.com/linuxkit/linuxkit) as well as the go bindings https://github.com/moby/hyperkit/blob/master/go/hyperkit.go have sample code for that

**Comment by copumpkin** [comment]
That's awesome, thanks! It still seems like ultimately VPNKit would need to be run with privileges though, right? But it would allow the individual HyperKit invocations to avoid being privileged?

cc @LnL7 who's probably also interested

**Comment by rneugeba** [comment]
No, VPNKit does not need to run with privileges because it just re-opens TCP/UDP connections as normal sockets. It also has functionality to listen on local ports and forward connections to the VM, again no privileges  needed  unless the ports are privileged.

**Comment by copumpkin** [comment]
That sounds perfect, thanks!
