### ISSUE TITLE
Can't boot Alpine Linux on Hyperkit

### ISSUE THREAD

**Issue by philnalwalker** [moby/hyperkit#156]
Trying to run Alpine Linux on Hyperkit. Get a "failed" error when running.

Macos Sierra + Hyperkit build from master.

install.sh

`
KERNEL="mnt/boot/vmlinuz-virthardened"
INITRD="mnt/boot/initramfs-virthardened"
CMDLINE="alpine_dev=cdrom:iso9660 modules=af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,earlyprintk=serial console=ttyS0"
MEM="-m 8G"
SMP="-c 4"
NET="-s 2:0,virtio-net"
IMG_CD="-s 3,ahci-cd,alpine-virt-3.6.2-x86_64.iso"
IMG_HDD="-s 4,virtio-blk,hdd.img"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"
ACPI="-A"
#UUID="-U FBD1B520-3130-488A-A4E4-AC490BDAC231"
hyperkit $ACPI $UUID $SMP $MEM $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE" -w
`

run.sh

`
KERNEL="vmlinuz-virthardened"
INITRD="initramfs-virthardened"
CMDLINE="earlyprintk=serial console=ttyS0 modules=af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,ext4"
MEM="-m 8G"
#SMP="-c 4"
NET="-s 2:0,virtio-net"
#IMG_CD="-s 3,ahci-cd,alpine-3.2.3-x86_64.iso"
IMG_HDD="-s 4,virtio-blk,hdd.img"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"
ACPI="-A"
hyperkit $ACPI $SMP $MEM $PCI_DEV $LPC_DEV $NET $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE" -w
`

Kernel output

`
[    0.000000] Linux version 4.9.32-0-virthardened (buildozer@build-3-6-x86_64) (gcc version 6.3.0 (Alpine 6.3.0) ) #1-Alpine SMP Fri Jun 16 12:39:17 GMT 2017
[    0.000000] Command line: earlyprintk=serial console=ttyS0 modules=af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,ext4
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] x86/fpu: Using 'eager' FPU context switches.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bfffffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000023fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.6 present.
[    0.000000] e820: last_pfn = 0x240000 max_arch_pfn = 0x400000000
[    0.000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] e820: last_pfn = 0xc0000 max_arch_pfn = 0x400000000
[    0.000000] Using GB pages for direct mapping
[    0.000000] RAMDISK: [mem 0x7fade000-0x7fffffff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x00000000000F2400 000024 (v02 BHYVE )
[    0.000000] ACPI: XSDT 0x00000000000F2480 000044 (v01 BHYVE  BVXSDT   00000001 INTL 20140828)
[    0.000000] ACPI: APIC 0x00000000000F2500 00005A (v01 BHYVE  BVMADT   00000001 INTL 20140828)
[    0.000000] ACPI: FACP 0x00000000000F2A00 00010C (v05 BHYVE  BVFACP   00000001 INTL 20140828)
[    0.000000] ACPI: DSDT 0x00000000000F2C00 000A2D (v02 BHYVE  BVDSDT   00000001 INTL 20140828)
[    0.000000] ACPI: FACS 0x00000000000F2BC0 000040
[    0.000000] ACPI: FACS 0x00000000000F2BC0 000040
[    0.000000] ACPI: HPET 0x00000000000F2B40 000038 (v01 BHYVE  BVHPET   00000001 INTL 20140828)
[    0.000000] ACPI: MCFG 0x00000000000F2B80 00003C (v01 BHYVE  BVMCFG   00000001 INTL 20140828)
[    0.000000] Setting APIC routing to physical flat.
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x000000023fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x00000000bfffffff]
[    0.000000]   node   0: [mem 0x0000000100000000-0x000000023fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x000000023fffffff]
[    0.000000] ACPI: PM-Timer IO Port: 0x408
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] high edge lint[0x1])
[    0.000000] IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 high edge)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x80860701 base: 0xfed00000
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] e820: [mem 0xc0000000-0xffffffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.000000] setup_percpu: NR_CPUS:32 nr_cpumask_bits:32 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] percpu: Embedded 32 pages/cpu @ffff88023fc00000 s91352 r8192 d31528 u2097152
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 2064265
[    0.000000] Kernel command line: earlyprintk=serial console=ttyS0 modules=af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,ext4
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Dentry cache hash table entries: 1048576[    0.002270] ACPI: 1 ACPI AML tables successfully acquired and loaded
[    0.002771] Mount-cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.003219] Mountpoint-cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.004511] CPU: Physical Processor ID: 0
[    0.004847] PAX: PCID detected
[    0.005059] Last level iTLB entries: 4KB 64, 2MB 8, 4MB 8
[    0.005492] Last level dTLB entries: 4KB 64, 2MB 0, 4MB 0, 1GB 4
[    0.032310] Freeing SMP alternatives memory: 20K (ffffffff81a10000 - ffffffff81a15000)
[    0.045581] smpboot: Max logical packages: 1
[    0.046937] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.261852] smpboot: CPU0: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (family: 0x6, model: 0x5e, stepping: 0x3)
[    0.262599] Performance Events: unsupported p6 CPU model 94 no PMU driver, software events only.
[    0.263735] NMI watchdog: disabled (cpu0): hardware events not enabled
[    0.264166] NMI watchdog: Shutting down hard lockup detector on all cpus
[    0.264684] x86: Booted up 1 node, 1 CPUs
[    0.264949] ----------------
[    0.265156] | NMI testsuite:
[    0.265358] --------------------
[    0.265547]   remote IPI:  ok  |
[    0.265753]    local IPI:  ok  |
[    0.266015] --------------------
[    0.266201] Good, all   2 testcases passed! |
[    0.266450] ---------------------------------
[    0.266700] smpboot: Total of 1 processors activated (5424.00 BogoMIPS)
[    0.267512] devtmpfs: initialized
[    0.267807] x86/mm: Memory block size: 128MB
[    0.269798] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.270422] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.270941] NET: Registered protocol family 16
[    0.271419] cpuidle: using governor ladder
[    0.271718] cpuidle: using governor menu
[    0.272014] ACPI FADT declares the system doesn't support PCIe ASPM, so disable it
[    0.272630] ACPI: bus type PCI registered
[    0.272903] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    0.273577] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xe0000000-0xefffffff] (base 0xe0000000)
[    0.274231] PCI: not using MMCONFIG
[    0.274436] PCI: Using configuration type 1 for base access
[    0.281669] HugeTLB registered 1 GB page size, pre-allocated 0 pages
[    0.282118] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.282698] ACPI: Added _OSI(Module Device)
[    0.282926] ACPI: Added _OSI(Processor Device)
[    0.283162] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.283411] ACPI: Added _OSI(Processor Aggregator Device)
[    0.284079] ACPI: Interpreter enabled
[    0.284285] ACPI: (supports S0 S5)
[    0.284468] ACPI: Using IOAPIC for interrupt routing
[    0.284760] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xe0000000-0xefffffff] (base 0xe0000000)
[    0.285334] PCI: MMCONFIG at [mem 0xe0000000-0xefffffff] reserved in ACPI motherboard resources
[    0.285880] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.287149] ACPI: PCI Root Bridge [PC00] (domain 0000 [bus 00])
[    0.287469] acpi PNP0A03:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI]
[    0.287994] acpi PNP0A03:00: _OSC failed (AE_NOT_FOUND); disabling ASPM
[  7 9 10 11 12 14 15) *0, disabled.
[    0.299122] ACPI: PCI Interrupt Link [LNKF] (IRQs 3 4 5 6 7 9 10 11 12 14 15) *0, disabled.
[    0.300011] ACPI: PCI Interrupt Link [LNKG] (IRQs 3 4 5 6 7 9 10 11 12 14 15) *0, disabled.
[    0.300798] ACPI: PCI Interrupt Link [LNKH] (IRQs 3 4 5 6 7 9 10 11 12 14 15) *0, disabled.
[    0.301721] SCSI subsystem initialized
[    0.302583] PCI: Using ACPI for IRQ routing
[    0.337687] clocksource: Switched to clocksource hpet
[    0.338009] VFS: Disk quotas dquot_6.6.0
[    0.338239] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.338668] pnp: PnP ACPI init
[    0.339022] system 00:00: [io  0x0220-0x0223] has been reserved
[    0.339364] system 00:00: [io  0x0224-0x0227] has been reserved
[    0.339702] system 00:00: [io  0x04d0-0x04d1] has been reserved
[    0.340039] system 00:00: [io  0x0400-0x0407] has been reserved
[    0.340407] system 00:00: [mem 0xe0000000-0xefffffff] has been reserved
[    0.340917] pnp: PnP ACPI: found 4 devices
[    0.347983] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    0.348563] pci 0000:00:02.0: BAR 6: assigned [mem 0xc0004000-0xc00047ff pref]
[    0.348955] pci 0000:00:04.0: BAR 6: assigned [mem 0xc0004800-0xc0004fff pref]
[    0.349346] pci 0000:00:1f.0: BAR 6: assigned [mem 0xc0005000-0xc00057ff pref]
[    0.349817] NET: Registered protocol family 2
[    0.350193] TCP established hash table entries: 65536 (order: 7, 524288 bytes)
[    0.351097] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    0.352342] TCP: Hash tables configured (established 65536 bind 65536)
[    0.352724] UDP hash table entries: 4096 (order: 5, 131072 bytes)
[    0.353074] UDP-Lite hash table entries: 4096 (order: 5, 131072 bytes)
[    0.353601] NET: Registered protocol family 1
[    0.353873] pci 0000:00:1f.0: Activating ISA DMA hang workarounds
[    0.355897] Unpacking initramfs...
[    0.446953] Freeing initrd memory: 5256K (ffff88007fade000 - ffff880080000000)
[    0.447632] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.448261] software IO TLB [mem 0xbc000000-0xc0000000] (64MB) mapped at [ffff8800bc000000-ffff8800bfffffff]
rdmsr to register 0x64e on vcpu 0
                                 rdmsr to register 0x34 on vcpu 0
                                                                 [    0.449793] workingset: timestamp_bits=46 max_order=21 bucket_order=0
[    0.450569] Key type asymmetric registered
[    0.450841] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.451334] io scheduler noop registered
[    0.451580] io scheduler deadline registered (default)
[    0.451944] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    0.452277] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    0.452660] ERST DBG: ERST support is disabled.
[    0.452924] xenfs: not registering filesystem on non-xen platform
[    0.453380] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.475997] 00:01: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    0.497906] 00:02: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[    0.499010] VMware PVSCSI driver - version 1.0.7.0-k
[    0.499421] i8042: PNP: No PS/2 controller found. Probing ports directly.
[    1.026258] i8042: Can't read CTR while initializing i8042
[    1.026851] i8042: probe of i8042 failed with error -5
[    1.027324] ACPI Error: Could not enable RealTimeClock event (20160831/evxfevnt-212)
[    1.027863] ACPI Warning: Could not enable fixed event - RealTimeClock (4) (20160831/evxface-654)
[    1.029069] rtc_cmos 00:03: rtc core: registered rtc_cmos as rtc0
[    1.029628] rtc_cmos 00:03: alarms up to one day, y3k, 114 bytes nvram
[    1.030121] gre: GRE over IPv4 demultiplexor driver
[    1.030462] Key type dns_resolver registered
[    1.030975] registered taskstats version 1
[    1.031382] rtc_cmos 00:03: setting system clock to 2017-09-22 23:42:27 UTC (1506123747)
[    1.032394] Freeing unused kernel memory: 1144K (ffffffff818f2000 - ffffffff81a10000)
[    1.032839] Write protecting the kernel read-only data: 8192k
[    1.033237] Freeing unused kernel memory: 76K (ffff8800015ed000 - ffff880001600000)
[    1.034042] Freeing unused kernel memory: 220K (ffff8800017c9000 - ffff880001800000)
Alpine Init 3.1.0-r3
 * Loading boot drivers: [    1.042033] loop: module loaded
[    1.045031] ACPI: bus type USB registered
[    1.045274] usbcore: registered new interface driver usbfs
[    1.045569] usbcore: registered new interface driver hub
[    1.045863] usbcore: registered new device driver usb
[    1.047078] usbcore: registered new interface driver usb-storage
ok.
 * Mounting boot media: [    1.066929] virtio-pci 0000:00:02.0: virtio_pci: leaving for legacy driver
[    1.067488] virtio-pci 0000:00:04.0: virtio_pci: leaving for legacy driver
[    1.077376]  vda: vda1 vda2 vda3
[    1.488851] tsc: Refined TSC clocksource calibration: 2710.056 MHz
[    1.489786] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x27105a0899e, max_idle_ns: 440795341951 ns
[    1.602975] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: (null)
[    1.615969] EXT4-fs (vda3): mounted filesystem with ordered data mode. Opts: (null)
[    1.619363] random: fast init done
[    2.496167] clocksource: Switched to clocksource tsc
failed.
initramfs emergency recovery shell launched. Type 'exit' to continue boot
sh: can't access tty; job control turned off
/ #
`

**Comment by rn** [comment]
From the boot log, it looks like this portion from the `init` script failed:
```
ebegin "Mounting boot media"
nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
	${KOPT_usbdelay:+-t $(( $KOPT_usbdelay * 1000 ))} \
	$repoopts -a /tmp/apkovls
eend $?
```
maybe specify `debug_init` on the kernel command line (not sure what the correct syntax is).

Your snippets above on how you invoke hyperkit are really hard to read, they seem to be missing line breaks...and there are two snippets and it's not clear which one produced the output or how you boot in general. The Alpine virt image is an iso, which you can't boot on HyperKit (unless it's an EFI ISO, which it does now seem to be)

**Comment by philnalwalker** [comment]
Managed to get it working.

install.sh:

`
KERNEL="mnt/boot/vmlinuz-hardened"
INITRD="mnt/boot/initramfs-hardened"
CMDLINE="alpine_dev=cdrom:iso9660 modules=af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,earlyprintk=serial console=ttyS0"
MEM="-m 8G"
SMP="-c 4"
NET="-s 2:0,virtio-net"
IMG_CD="-s 3,ahci-cd,alpine-standard-3.6.2-x86_64.iso"
IMG_HDD="-s 4,virtio-blk,hdd.img"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"
ACPI="-A"
UUID="-U deadbeef-dead-beef-dead-beef00000000"
hyperkit $ACPI $UUID $SMP $MEM $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE" -w
`

run.sh:

`
KERNEL="mnt/boot/vmlinuz-hardened"
INITRD="mnt/boot/initramfs-hardened"
CMDLINE="earlyprintk=serial console=ttyS0 modules=virtio_blk,af_socket,loop,squashfs,sd-mod,usb-storage,sr-mod,ext4 debug_init root=/dev/vda3"
MEM="-m 8G"
#SMP="-c 4"
NET="-s 2:0,virtio-net"
IMG_HDD="-s 4,virtio-blk,hdd.img"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"
ACPI="-A"
UUID="-U deadbeef-dead-beef-dead-beef00000000"
hyperkit $UUID $ACPI $SMP $MEM $PCI_DEV $LPC_DEV $NET $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE" -w
`
