### ISSUE TITLE
Docker Network Not Operating Harmoniously with Ethernet and Proxy

### ISSUE THREAD

**Issue by loopy3025** [moby/hyperkit#193]
Hello. I have run into an issue. Our organization uses z-scaler for a network proxy. We have gotten Docker with Docksal working to run our Drupal websites on our local Windows development machines. We're mighty chuffed about this, but there's one issue. When we try to push and pull to and from GitHub and the Docker repos, we can't establish a connection. We also can't access most content via port 80 except for locations that are explicitly whitelisted by our proxy.  We ARE able to access them with Docker disabled, but of course our dev sites can't be accessed with Docker turned off. So it seems to me there's some kind of specific user permissions which are not being picked up from Windows by Docker in order to access these resources while it is running.

Specifically, enabling DockerNAT causes me to lose access to most internet locations through my browser and command line. Disabling it restores that access. Is there some kind of setting in the DockerNAT connection that needs to be configured to work between Docker and my proxy?

I also see that I have an Ethernet connection in my list of network connections and a vEthernet (HNS Internal NIC). Does one of those have to be disabled and/or enabled in order for DockerNAT to run harmoniously?

Note: we do have the "Manual proxy configuration" set under Settings > Proxies for Docker and we have proxy settings set for both babun and git.

Does anyone have any thoughts or guidance in regards to this issue. It's certainly vexing.

**Comment by ijc** [comment]
Please file an issue against whichever of [`docker/for-mac`](https://github.com/docker/for-mac) and [`docker/for-win`](https://github.com/docker/for-win) is most appropriate (it wasn't clear to me which you are using). 

Hyperkit is the hypervisor component of `docker/for-mac` (*not* `docker/for-win`) and the networking behaviour you describe is not something which immediately seems to be in Hyperkit's domain.
