### ISSUE TITLE
Support for fsync() on shared directories?

### ISSUE THREAD

**Issue by gintautassulskus** [moby/hyperkit#198]
Hi,

Does hyperkit support fsync on shared directories?
I am having issues with MongoDB that [requires this functionality](https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories). 

Thanks,
Gintas

**Comment by rn** [comment]
Shared directories is not a feature of `hyperkit` and `fsync` is a OS level function which `hyperkit` knows nothing about (it only handles block devices), so I'm closing this issue here. If this question is related to Docker for Mac, please file an issue on https://github.com/docker/for-mac/
