### ISSUE TITLE
Command option to get the mac address

### ISSUE THREAD

**Issue by frezbo** [moby/hyperkit#236]
`xhyve` has a command line option **-M** to get the mac address of the created VM, does `hyperkit` support any such functionality?

**Comment by ijc** [comment]
`hyperkit` currently does not have an option like that.

Depending on the network back you are using some of them have a mechanism to set the mac address from the command line and others have options to write the assigned mac to a file etc but there is nothing which is global. The only reference for which backend supports what is the code I'm afraid.
