### ISSUE TITLE
Hyperkit logs strange messages, "Docker for Mac" hangs

### ISSUE THREAD

**Issue by joeperks** [moby/hyperkit#238]
**Expected Behavior:** Docker for Mac to start

**Observed Behavior:** Docker for Mac displays "Starting Up", never starts; hyperkit prints strange log messages (below).

**Troubleshooting steps taken:** Checked permissions on Application, all looked fine, all owned by my user. Attempted to read logs, but found below output.

<img width="1386" alt="screen shot 2018-12-07 at 10 38 18 am" src="https://user-images.githubusercontent.com/21244349/49657015-a9325600-fa0c-11e8-8931-3d3a9279714d.png">

**Comment by ijc** [comment]
I think those are just ANSI escape codes from the VM console being logged (and obscuring the real messages).

Since this is a Docker for Mac issue, please open an issue on https://github.com/docker/for-mac/ so the right teams will see it.
