### ISSUE TITLE
Could you please tag a new release to include Catalina fix?

### ISSUE THREAD

**Issue by mjgallag** [moby/hyperkit#267]
Note that the version of hyperkit (`v0.20190802-4-g97f091`) included in the latest stable version of Docker for Mac (`2.2.0.0 (42247)`) is built from the latest commit on master (https://github.com/moby/hyperkit/commit/97f091f9a65390123d96c6794a4b29190e04ce3d) so I assume it's stable enough to tag as a release. I'm specifically looking to get https://github.com/moby/hyperkit/pull/263 included in Homebrew's hyperkit formula to solve issues with minikube users who choose to install HyperKit Hypervisor via Homebrew rather than building it from GitHub or installing Docker for Mac, see https://minikube.sigs.k8s.io/docs/start/macos/. Once this is done I'll submit a PR to Homebrew to update the formula to the new release, see https://github.com/Homebrew/homebrew-core/pull/42724. Thanks!

**Comment by AkihiroSuda** [comment]
@justincormack PTAL?

**Comment by mjgallag** [comment]
bump

**Comment by djs55** [comment]
I've pushed a tag for 97f091f: https://github.com/moby/hyperkit/tree/v0.20200224 . Hope this helps! (... please re-open the issue if not)

**Comment by mjgallag** [comment]
@djs55 unfortunately Homebrew's build failed, see https://github.com/Homebrew/homebrew-core/pull/50655/checks?check_run_id=465632390, specifically:
```
==> opam config exec -- opam install -y uri.1.9.7 qcow.0.10.4 conduit.1.0.0 lwt.3.1.0 qcow-tool.0.10.5 mirage-block-unix.2.9.0 conf-libev.4-11 logs.0.6.3 fmt.0.8.6 mirage-unix.3.2.0 prometheus-app.0.5 cstruct-lwt.3.2.1
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value (currently, it is set to 60.0 seconds).
```

Any help greatly appreciated, thanks!

**Comment by djs55** [comment]
Hm, that's annoying. In future I hope to switch to vendoring for these dependencies which will remove the need for version constraint solving... however the tooling for that isn't quite ready.

I'm not familiar with the homebrew build process. Is it possible to set the `OPAMSOLVERTIMEOUT` to maybe `120`? I think it would have succeeded if it hadn't hit the timeout.

**Comment by mjgallag** [comment]
@djs55 thanks, that solved that problem, but unfortunately we've got a new error:
```
08:56:13 Error: An exception occurred within a child process:
08:56:13   TypeError: no implicit conversion of Integer into String
```
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=highsierra/57644/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=mojave/57644/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=catalina/57644/console

Would it be possible to tag a new release that includes your most recent fix https://github.com/moby/hyperkit/commit/908930c70f97db6a7159a3f05ef2457001944392?

**Comment by mjgallag** [comment]
@djs55 FYI, for reasons outside of my understanding this is building on `Homebrew` now without the above error, so your new tag is available there now, thanks! See https://github.com/Homebrew/homebrew-core/pull/50655#issuecomment-596823228 for details.

**Comment by mjgallag** [comment]
New version of `hyperkit` with Cataline fix is finally available on `Homebrew`, see https://github.com/Homebrew/homebrew-core/pull/50655 & https://github.com/moby/hyperkit/issues/267 for details.
