### ISSUE TITLE
Fails to start VM on Bigsur

### ISSUE THREAD

**Issue by acshekhara** [moby/hyperkit#300]
VM create fails with this error on bigSur. 
Processor : i9
hv_vm_create unknown error -85377023

Command : hyperkit -A -H -U 20DD5167-9FBE-439E-9849-E324E984FB96 -m 3GB -c 2 -s 0:0,hostbridge -s 2:0,virtio-net -s 31,lpc -l com1,stdio -s 1:0,ahci-hd,/ubuntu-18.04-server-cloudimg-amd64.raw -s 5,ahci-cd,/cloud-init.iso -f kexec,/ubuntu-18.04-server-cloudimg-amd64-vmlinuz-generic,/ubuntu-18.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/sda1

tag: v0.20200908

**Comment by rn** [comment]
Hyperkit shipping with docker desktop seems to work. Not sure if this is a special build

hyperkit: v0.20200224-44-gb54460

**Comment by acshekhara** [comment]
This is built using latest code.
commit b54460a1b41b487262d03c9685ae8b50dbc6607a (HEAD -> master, tag: v0.20200908, origin/master, origin/HEAD)

**Comment by apinske** [comment]
I encountered a similar problem, when linking against Hypervisor.framework on Big Sure, see: https://github.com/apinske/simpleos/tree/hvf_bug
Maybe that helps you.

**Comment by harishagrawal** [comment]
I am on latest BigSur as well and facing the same issue. Appreciate an early fix to this.

**Comment by ashvinsharma** [comment]
Same here

**Comment by townsend2010** [comment]
Probably need #295 to be merged.  I proposed that 3 months ago!

**Comment by townsend2010** [comment]
Or use Multipass for Mac (https://multipass.run) in which we've had this fixed for a while now :smile:

**Comment by rn** [comment]
@townsend2010 it fails before getting to that so I haven't been able to test...

**Comment by townsend2010** [comment]
@rn,

Ok, interesting.  Your issue is on Intel Mac or the new Apple Silicon?  I wonder why we've had success with just that change (on Intel hardware)?

**Comment by rn** [comment]
sadly I don't have M1 yet, so this is on a 2015 iMAC. It fails here: https://github.com/moby/hyperkit/blob/master/src/lib/vmm/intel/vmx.c#L474

which is the first init call. way before vCPU setp and XSAVE and friends come into play

**Comment by townsend2010** [comment]
@rm, I see.  Now that I'm actually groking the issue :smiley: , we have seen that particular error in a couple of user reports in Multipass: canonical/multipass#1652 and canonical/multipass#1839

It's still not clear to us what causes this for a small sample of our user base.

**Comment by djs55** [comment]
#295 is merged (sorry I hadn't spotted it)

**Comment by townsend2010** [comment]
@djs55,

Thanks for merging that!  I wish it fixed the issue here as I assumed, but alas not.

**Comment by townsend2010** [comment]
After a bit of research, this *might* be due to a missing `com.apple.security.hypervisor` entitlement.  See [here](https://stackoverflow.com/questions/64642062/apple-hypervisor-is-completely-broken-on-macos-big-sur-beta-11-0-1) for a possible solution.

**Comment by rn** [comment]
great find. This fixed it. I'll do a PR the tomorrow or so

**Comment by townsend2010** [comment]
Sweet! Glad that fixed it!
