### ISSUE TITLE
Hyperkit support on macos silicon (M1) processors

### ISSUE THREAD

**Issue by Dave-Dohmeier** [moby/hyperkit#310]
I'm using hyperkit as the driver on minikube currently and support seems to have been dropped for all drivers except docker when using a non-intel build of minikube. When testing on an M1 mac I can get hyperkit to build from source without problems. I built minikube from source and re-enabled hyperkit to see what would happen and it seems to be crashing.

This isn't so much a bug as I'm just looking for guidance or direction on getting hyperkit to work again on M1, or feedback on a timeline when it might become available as a driver for minikube again.

Thanks for any help or feedback.

**Comment by ncopa** [comment]
see https://github.com/moby/hyperkit/issues/303#issuecomment-875122919

**Comment by harishagrawal** [comment]
I have a similar dependency on hyperkit and it keeps crashing on m1. Appreciate if there is any roadmap for the support on m1

**Comment by rn** [comment]
hyperkit has many very x86 specific parts and is unlikely going to port to M1

**Comment by kevinGC** [comment]
I'm curious - how does Docker for Mac run on M1 given the lack of Hyperkit support?

**Comment by tristanmorgan** [comment]
I see com.docker.supervisor -> com.docker.driver.amd64-linux -> qemu-system-aarch64 running on an M1 for docker...

**Comment by Dave-Dohmeier** [comment]
> I'm curious - how does Docker for Mac run on M1 given the lack of Hyperkit support?

Docker for mac has been running pretty well. It looks like minikube has updated their support to both docker for mac and podman on M1
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/driver/driver_darwin.go#L28

My problem with docker for mac is that it doesn't really provide a networking bridge the way that hyperkit does, only port forwarding. This makes networking several containers for local dev quite painful, but there are work-arounds.

It looks like apples has gone all in on M1 and will not be using intel for any new hardware going forward.

**Comment by cscetbon** [comment]
@Dave-Dohmeier i started asking similar questions on the minijupe project and asked to add support for the new virtualization framework https://github.com/moby/hyperkit/issues/303#issuecomment-875122919

I'm probably gonna start working on it to add a driver for it which might interest others.

**Comment by greenchapter** [comment]
Hey, I also want to use hyperkit instead of docker for my M1 MacBook Pro, but I tried it actually to install under macOS Monterey and I wasn't very sucessful.

```brew install hyperkit```
```
Error: hyperkit: no bottle available!
You can try to install from source with:
  brew install --build-from-source hyperkit
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

Did someone has an idea?

**Comment by santiagoarizti** [comment]
I tried going to their github page and build from there. The build was successful (no errors, though suspiciously quick), then I added build/hyperkit to my $PATH but when I tried to use hyperkit with minikube it said: 
```
Exiting due to DRV_UNSUPPORTED_OS: The driver 'hyperkit' is not supported on darwin/arm64
```
Since I don't really know what I am doing I don't know if:

- the build was successful (i.e. not broken), but minikube doesn't want to use hyperkit anyways, or
- the build failed silently and minikube let me know it with that error message

**Comment by rn** [comment]
As mentioned above, hyperkit is x86 specific and I'm not aware of any plans to port this to M1, so closing this issues.

I can't tell for sure, but docker for mac now seems to offer a range of virtualisation backends, including one based on the new macOS virtualization framework, which is essentially most of the HyperKit functionality provided as an API and which works cross platform (x86/m1). The code for `com.docker.virtualization` which likely wraps the virtualization framework API calls does not seem to be open source, but there are several small code examples out there on how to write a VMM, like hyperkit, using the virtualisation framework  with just a few lines of code.

**Comment by 9527andy** [comment]
Hi @Dave-Dohmeier 
Do you have a solution to work on M1?

**Comment by djs55** [comment]
@Dave-Dohmeier regarding
> My problem with docker for mac is that it doesn't really provide a networking bridge the way that hyperkit does, only port forwarding. This makes networking several containers for local dev quite painful, but there are work-arounds.

Perhaps try Docker for Mac with the experimental `virtualization.framework` support enabled and then edit `~/Library/Group\ Containers/group.com.docker/settings.json` to have `"useVpnkit": false,` -- this will disable the userspace networking and use `vmnet.framework` instead. This will create kernel interfaces on the host but has a number of drawbacks

- routing problems with VPNs
- there's a fundamental clash between Apple Internet Connection Sharing and this feature

Let me know if it works for you! (This isn't regularly tested so there might be issues -- let me know if so)
