### ISSUE TITLE
unable to install hyperkit on apple silicon

### ISSUE THREAD

**Issue by npinnaka** [moby/hyperkit#314]
Installing hyperkit on mac 

$ brew install hyperkit

Error: hyperkit: no bottle available!
You can try to install from source with:
  brew install --build-from-source hyperkit
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

$ brew install --build-from-source hyperkit
conduit.2.1.0
lwt.5.3.0
qcow-tool.0.11.0
mirage-block-unix.2.12.0
conf-libev.4-11
logs.0.7.0
fmt.0.8.8
mirage-unix.4.0.0
prometheus-app.0.7

The following dependencies couldn't be met:
  - lwt → ocaml < 4.12
      base of this switch (use `--unlock-base' to force)

No solution found, exiting

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by rn** [comment]
Hyperkit does not support apple silicon. See https://github.com/moby/hyperkit/issues/310
