### ISSUE TITLE
Potential error due to the unreleased lock after program exit

### ISSUE THREAD

**Issue by jenny-cheung** [moby/hyperkit#316]
Hi, developers, before normal exit, the mutex is unlocked. However, in the method `echoer`, the lock `sync.e_mt` may still be held before the exit. It is not a very harmful bug( e.g., resource leak, deadlock) since the program exits and all of the program resources will be cleaned up by some common OS. However, other OS systems (e.g., embedded systems) do not automatically free some resources at the exit. It is a good manner for resource management. Adding the unlock statement adds symmetry, so the code looks better. Also, the debugger would not warn this case : )

https://github.com/moby/hyperkit/blob/2f061e447e1435cdf1b9eda364cea6414f2c606b/src/lib/mevent_test.c#L147

```
static void *
echoer(void *param)
{
	pthread_mutex_lock(&sync.e_mt);

	mev = mevent_add(fd, EVF_READ, echoer_callback, &sync);
	if (mev == NULL) {
		printf("Could not allocate echoer event\n");
		exit(1);
	}

	...;

	return (NULL);
}
```

Best,

**Comment by jenny-cheung** [comment]
Hi, developers @djs55  @fredericdalleau 
Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by fredericdalleau** [comment]
Hi @jenny-cheung, 
As you said, `exit()` leaves up to the os to clean everything. If a random OS does not properly free the ressources, it's a problem on this OS and it's not supported as per the requirements.
Wrt coding-style, `mevent_test.c` comes from an external library that has been integrated into this project, we 'd rather avoid carrying patches on top of it just for this sole purpose.
Best regards,

**Comment by jenny-cheung** [comment]
@fredericdalleau
Thank you for your reply and confirmation. This is a small error and harmless for most OS, so I understand why you won't fix it.
