### ISSUE TITLE
LICENSE / COPYING missing

### ISSUE THREAD

**Issue by buforo** [moby/hyperkit#327]
Hello,

I am new at github. I just tested this, it works for me on big Sur (networking is still a problem, I have to figure out where to find infos about how to use virtio-net). To use this, it is important for me, to know the copying/license conditions. (xhyve has a LICENSE file.) Is this intentionally omitted here, or did I just not find the equivalent ? If it's ommited: where are possible problems ? Hope I did this issue right - Thanks in advance ?

**Comment by rn** [comment]
The README has a license at the end

**Comment by mat007** [comment]
Hi!

I opened #331 to address this, as I stumbled upon it as well.
Out of almost 2000 dependencies in my application this was one of only 4 projects (and the only one on GitHub) for which the license detection didn’t work out of the box.

I realize this is pretty minor, and it’s not really a blocker for me, as I can always manually override the license detection on my end, but it’s a small change anyway. 😁
